### PR TITLE
documentation: using mkdocs

### PR DESCRIPTION
**Pull request by marianfoo**
## Using Material for Mkdocs to visualize the documentation better:
To view docs locally run from root:
`docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material`. 
open `http://localhost:8000/ui5-test-runner/`

image

## Settings --> Pages
image

## Under Settings --> Actions --> General
image

## Show in `About` section
I also would suggest showing the URL to the documentation in the about section of the repo like here:
image

### CODE REVIEW

**Comment by ArnaudBuchholz** [comment]
Thx for the submission, I will double check that !

**Review by ArnaudBuchholz — APPROVED** [review]
New to me but willing to try !

**Comment by marianfoo** [comment]
Thanks, i used it for my Excel Upload Component but adopted it from Ui5 tooling. They use the same setup.
Now you can setup the pages to run from the branch `gh-pages`

**Comment by ArnaudBuchholz** [comment]
I like the result, thx again !

**Comment by marianfoo** [comment]
Looks good!
You can add the url to the `About` section to your GitHub Repo, so it's better visible.

**Comment by ArnaudBuchholz** [comment]
Done !

**Pull request merged**
